# Generated by Django 4.1.7 on 2023-03-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.CharField(max_length=20)),
                ('shareTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharedTo', to='myapp.user')),
                ('sharedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharedBy', to='myapp.user')),
            ],
        ),
    ]
