# Generated by Django 4.1.7 on 2023-03-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='shareTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareTo', to='myapp.user'),
        ),
    ]
