# Generated by Django 4.1.7 on 2023-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='imagelink',
            field=models.CharField(max_length=100),
        ),
    ]
